version: '3.3'

networks:
  default:
    ipam:
      config:
        - subnet: 10.100.4.0/24
  traefik_webproxy:
    external: true

services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-toor}
    command: --innodb-doublewrite=0
    volumes:
      - /var/lib/pimcore-mysql:/var/lib/mysql
    logging:
      driver: syslog
      options:
        tag: pimcore-mysql
        syslog-address: "tcp://192.168.250.21:514"
    deploy:
      placement:
        constraints: [node.hostname == manager-1]

  mailcatcher:
    image: schickling/mailcatcher
    logging:
      driver: syslog
      options:
        tag: pimcore-mailcatcher
        syslog-address: "tcp://192.168.250.21:514"

  application:
    image: blackikeeagle/swarm-pimcore-demo-php:0.0.2
    environment:
      - DEVELOPMENT=noprofile # we want to use mailcatcher in the demo
    volumes:
      - /srv/storage/pimcore/web-var:/phpapp/web/var
      - /srv/storage/pimcore/var:/phpapp/var
    logging:
      driver: syslog
      options:
        tag: pimcore-application
        syslog-address: "tcp://192.168.250.21:514"
    deploy:
      replicas: 1

  cron:
    image: blackikeeagle/swarm-pimcore-demo-php:0.0.2
    environment:
      - DEVELOPMENT=noprofile # we want to use mailcatcher in the demo
      - "CRON=0 */5 * * * *"
    command: php bin/console maintenance
    volumes:
      - /srv/storage/pimcore/web-var:/phpapp/web/var
      - /srv/storage/pimcore/var:/phpapp/var
    logging:
      driver: syslog
      options:
        tag: pimcore-cron
        syslog-address: "tcp://192.168.250.21:514"

  nginx:
    image: blackikeeagle/swarm-pimcore-demo-nginx:0.0.0
    volumes:
      - /srv/storage/pimcore/web-var:/phpapp/web/var
    networks:
      - default
      - traefik_webproxy
    logging:
      driver: syslog
      options:
        tag: pimcore-nginx
        syslog-address: "tcp://192.168.250.21:514"
    deploy:
      replicas: 2
      labels:
        # tell traefik to route to the container
        - "traefik.enable=true"
        # a name for this application in traefik, must be unique
        - "traefik.backend=pimcore"
        # hostnames to route to this container (and retrieve ssl certs for)
        - "traefik.frontend.rule=Host:pimcore-demo.test"
        # network this container is attached to (global name)
        - "traefik.docker.network=traefik_webproxy"
        # port this container listens on
        - "traefik.port=80"
