version: "3.3"

networks:
  webproxy:
    driver: overlay
    attachable: true

configs:
  traefik_config:
    file: ./config.toml

services:
  traefik:
    image: traefik:roquefort-alpine
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: ingress
      - target: 443
        published: 443
        protocol: tcp
        mode: ingress
      - target: 8080
        published: 8080
        protocol: tcp
        mode: ingress
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - webproxy
    configs:
      - source: traefik_config
        target: /etc/traefik/traefik.toml
        uid: '1'
        gid: '1'
        mode: 0700
    deploy:
      placement:
        constraints: [node.role == manager]

