version: '3.3'

networks:
  default:
    ipam:
      config:
        - subnet: 10.100.1.0/24

services:
  visualizer:
    image: dockersamples/visualizer
    ports:
      - target: 8080
        published: 8081
        protocol: tcp
        mode: ingress
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
    deploy:
      placement:
        constraints: [node.role == manager]

