version: '3.3'

networks:
  default:
    ipam:
      config:
        - subnet: 10.100.4.0/24

volumes:
  portainer:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.250.21,rw
      device: ":/srv/storage/portainer"

services:
  agent:
    image: portainer/agent
    environment:
      # REQUIRED: Should be equal to the service name prefixed by "tasks." when
      # deployed inside an overlay network
      AGENT_CLUSTER_ADDR: tasks.agent
      # AGENT_PORT: 9001
      # LOG_LEVEL: debug
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: /var/lib/docker/volumes
        target: /var/lib/docker/volumes
    deploy:
      mode: global

  portainer:
    image: portainer/portainer
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      - target: 9000
        published: 9000
        protocol: tcp
        mode: ingress
    volumes:
      - type: volume
        source: portainer
        target: /data
        volume:
          nocopy: true
    deploy:
      placement:
        constraints: [node.role == manager]

