version: '3.3'

networks:
  default:
    ipam:
      config:
        - subnet: 10.110.3.0/24
  traefik_webproxy:
    external: true

services:
  redis:
    image: redis:alpine
    volumes:
      - /srv/storage/magento2/redis:/data
    logging:
      driver: syslog
      options:
        tag: magento-redis
        syslog-address: "tcp://192.168.250.21:514"

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=toor
    command: --innodb-doublewrite=0
    volumes:
      - /var/lib/magento2-mysql:/var/lib/mysql
    logging:
      driver: syslog
      options:
        tag: magento-mysql
        syslog-address: "tcp://192.168.250.21:514"
    deploy:
      placement:
        constraints: [node.hostname == manager-2]

  mailcatcher:
    image: schickling/mailcatcher
    logging:
      driver: syslog
      options:
        tag: magento-mailcatcher
        syslog-address: "tcp://192.168.250.21:514"

  application:
    image: blackikeeagle/swarm-magento2-demo-php:0.0.2
    environment:
      - DEVELOPMENT=noprofile # we want to use mailcatcher in the demo
    volumes:
      - /srv/storage/magento2/env.php:/phpapp/app/etc/env.php
      - /srv/storage/magento2/var:/phpapp/var
      - /srv/storage/magento2/media:/phpapp/pub/media
    logging:
      driver: syslog
      options:
        tag: magento-application
        syslog-address: "tcp://192.168.250.21:514"
    deploy:
      replicas: 4

  cron:
    image: blackikeeagle/swarm-magento2-demo-php:0.0.2
    environment:
      - DEVELOPMENT=noprofile # we want to use mailcatcher in the demo
      - "CRON=0 * * * * *"
    command: php bin/magento cron:run
    volumes:
      - /srv/storage/magento2/env.php:/phpapp/app/etc/env.php
      - /srv/storage/magento2/var:/phpapp/var
      - /srv/storage/magento2/media:/phpapp/pub/media
    logging:
      driver: syslog
      options:
        tag: magento-cron
        syslog-address: "tcp://192.168.250.21:514"

  nginx:
    image: blackikeeagle/swarm-magento2-demo-nginx:0.0.2
    volumes:
      - /srv/storage/magento2/media:/phpapp/pub/media
    networks:
      - default
      - traefik_webproxy
    logging:
      driver: syslog
      options:
        tag: magento-nginx
        syslog-address: "tcp://192.168.250.21:514"
    deploy:
      labels:
        # tell traefik to route to the container
        - "traefik.enable=true"
        # a name for this application in traefik, must be unique
        - "traefik.backend=magento2"
        # hostnames to route to this container (and retrieve ssl certs for)
        - "traefik.frontend.rule=Host:magento2-demo.test"
        # network this container is attached to (global name)
        - "traefik.docker.network=traefik_webproxy"
        # port this container listens on
        - "traefik.port=80"
